package helpers;

import java.util.HashMap;

/**
 * Created by Birthright on 13.10.2015.
 */
public class HPCalculatorInfo {
    private static HashMap<String, HashMap<String, Double>> info = new HashMap<>();

    public static void createInfo() {

        HashMap<String, Double> rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 20.0);
        rate.put("3", 25.0);
        rate.put("4", 60.0);
        rate.put("5", 120.0);
        info.put("1", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 21.0);
        rate.put("3", 30.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("2", rate);
        rate = new HashMap<>();
        rate.put("1", 14.0);
        rate.put("2", 24.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("3", rate);
        rate = new HashMap<>();
        rate.put("1", 14.0);
        rate.put("2", 27.0);
        rate.put("3", 48.0);
        rate.put("4", 71.0);
        rate.put("5", 102.0);
        info.put("4", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 25.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("5", rate);
        rate = new HashMap<>();
        rate.put("1", 7.0);
        rate.put("2", 18.0);
        rate.put("3", 40.0);
        rate.put("4", 75.0);
        rate.put("5", 100.0);
        info.put("6", rate);
        rate = new HashMap<>();
        rate.put("1", 20.0);
        rate.put("2", 28.0);
        rate.put("3", 40.0);
        rate.put("4", 60.0);
        rate.put("5", 120.0);
        info.put("7", rate);
        rate = new HashMap<>();
        rate.put("1", 7.5);
        rate.put("2", 17.5);
        rate.put("3", 35.0);
        rate.put("4", 67.5);
        rate.put("5", 150.0);
        info.put("8", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("9", rate);
        rate = new HashMap<>();
        rate.put("1", 20.0);
        rate.put("2", 30.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("10", rate);
        rate = new HashMap<>();
        rate.put("1", 8.0);
        rate.put("2", 16.0);
        rate.put("3", 40.0);
        rate.put("4", 60.0);
        rate.put("5", 95.0);
        info.put("11", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 7.0);
        rate.put("3", 15.0);
        rate.put("4", 25.0);
        rate.put("5", 50.0);
        info.put("12", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 17.0);
        rate.put("3", 20.0);
        rate.put("4", 50.0);
        rate.put("5", 100.0);
        info.put("13", rate);
        rate = new HashMap<>();
        rate.put("1", 10.5);
        rate.put("2", 14.5);
        rate.put("3", 35.0);
        rate.put("4", 52.5);
        rate.put("5", 105.0);
        info.put("14", rate);
        rate = new HashMap<>();
        rate.put("1", 7.0);
        rate.put("2", 15.0);
        rate.put("3", 35.0);
        rate.put("4", 65.0);
        rate.put("5", 130.0);
        info.put("15", rate);
        rate = new HashMap<>();
        rate.put("1", 2.5);
        rate.put("2", 15.0);
        rate.put("3", 35.0);
        rate.put("4", 66.0);
        rate.put("5", 147.0);
        info.put("16", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 25.0);
        rate.put("3", 40.0);
        rate.put("4", 60.0);
        rate.put("5", 120.0);
        info.put("17", rate);
        rate = new HashMap<>();
        rate.put("1", 8.0);
        rate.put("2", 17.0);
        rate.put("3", 35.0);
        rate.put("4", 60.0);
        rate.put("5", 100.0);
        info.put("18", rate);
        rate = new HashMap<>();
        rate.put("1", 7.0);
        rate.put("2", 14.0);
        rate.put("3", 25.0);
        rate.put("4", 60.0);
        rate.put("5", 150.0);
        info.put("19", rate);
        rate = new HashMap<>();
        rate.put("1", 8.0);
        rate.put("2", 14.0);
        rate.put("3", 45.0);
        rate.put("4", 68.0);
        rate.put("5", 135.0);
        info.put("20", rate);
        rate = new HashMap<>();
        rate.put("1", 20.0);
        rate.put("2", 30.0);
        rate.put("3", 44.0);
        rate.put("4", 60.0);
        rate.put("5", 120.0);
        info.put("21", rate);
        rate = new HashMap<>();
        rate.put("1", 14.0);
        rate.put("2", 26.8);
        rate.put("3", 38.0);
        rate.put("4", 60.0);
        rate.put("5", 120.0);
        info.put("22", rate);
        rate = new HashMap<>();
        rate.put("1", 12.0);
        rate.put("2", 25.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("23", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 14.5);
        rate.put("3", 29.0);
        rate.put("4", 51.0);
        rate.put("5", 102.0);
        info.put("24", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 27.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("25", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 22.0);
        rate.put("3", 40.0);
        rate.put("4", 70.0);
        rate.put("5", 150.0);
        info.put("26", rate);
        rate = new HashMap<>();
        rate.put("1", 18.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("27", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 28.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("28", rate);
        rate = new HashMap<>();
        rate.put("1", 6.0);
        rate.put("2", 8.0);
        rate.put("3", 12.0);
        rate.put("4", 18.0);
        rate.put("5", 36.0);
        info.put("29", rate);
        rate = new HashMap<>();
        rate.put("1", 12.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("30", rate);
        rate = new HashMap<>();
        rate.put("1", 7.0);
        rate.put("2", 32.0);
        rate.put("3", 47.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("31", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 15.0);
        rate.put("3", 25.0);
        rate.put("4", 40.0);
        rate.put("5", 80.0);
        info.put("32", rate);
        rate = new HashMap<>();
        rate.put("1", 0.0);
        rate.put("2", 0.0);
        rate.put("3", 25.0);
        rate.put("4", 25.0);
        rate.put("5", 50.0);
        info.put("33", rate);
        rate = new HashMap<>();
        rate.put("1", 22.5);
        rate.put("2", 31.5);
        rate.put("3", 45.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("34", rate);
        rate = new HashMap<>();
        rate.put("1", 18.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("35", rate);
        rate = new HashMap<>();
        rate.put("1", 6.0);
        rate.put("2", 10.0);
        rate.put("3", 30.0);
        rate.put("4", 60.0);
        rate.put("5", 150.0);
        info.put("36", rate);
        rate = new HashMap<>();
        rate.put("1", 7.0);
        rate.put("2", 15.0);
        rate.put("3", 30.0);
        rate.put("4", 45.0);
        rate.put("5", 90.0);
        info.put("37", rate);
        rate = new HashMap<>();
        rate.put("1", 0.0);
        rate.put("2", 15.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("38", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 26.0);
        rate.put("3", 40.0);
        rate.put("4", 60.0);
        rate.put("5", 120.0);
        info.put("39", rate);
        rate = new HashMap<>();
        rate.put("1", 20.0);
        rate.put("2", 28.0);
        rate.put("3", 42.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("40", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 30.0);
        rate.put("3", 50.0);
        rate.put("4", 58.0);
        rate.put("5", 58.0);
        info.put("41", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 20.0);
        rate.put("3", 30.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("42", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 25.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("43", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 15.0);
        rate.put("3", 40.0);
        rate.put("4", 60.0);
        rate.put("5", 100.0);
        info.put("44", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 14.0);
        rate.put("3", 20.0);
        rate.put("4", 45.0);
        rate.put("5", 120.0);
        info.put("45", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("46", rate);
        rate = new HashMap<>();
        rate.put("1", 9.0);
        rate.put("2", 17.0);
        rate.put("3", 24.3);
        rate.put("4", 36.45);
        rate.put("5", 72.9);
        info.put("47", rate);
        rate = new HashMap<>();
        rate.put("1", 8.0);
        rate.put("2", 10.0);
        rate.put("3", 35.0);
        rate.put("4", 50.0);
        rate.put("5", 105.0);
        info.put("48", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 7.0);
        rate.put("3", 10.0);
        rate.put("4", 30.0);
        rate.put("5", 40.0);
        info.put("49", rate);
        rate = new HashMap<>();
        rate.put("1", 9.0);
        rate.put("2", 18.0);
        rate.put("3", 38.0);
        rate.put("4", 71.0);
        rate.put("5", 110.0);
        info.put("50", rate);
        rate = new HashMap<>();
        rate.put("1", 6.0);
        rate.put("2", 30.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("51", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 20.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("52", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 7.0);
        rate.put("3", 15.0);
        rate.put("4", 20.0);
        rate.put("5", 50.0);
        info.put("53", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 50.0);
        rate.put("5", 90.0);
        info.put("54", rate);
        rate = new HashMap<>();
        rate.put("1", 14.4);
        rate.put("2", 21.6);
        rate.put("3", 31.6);
        rate.put("4", 63.3);
        rate.put("5", 119.4);
        info.put("55", rate);
        rate = new HashMap<>();
        rate.put("1", 14.4);
        rate.put("2", 21.6);
        rate.put("3", 31.6);
        rate.put("4", 63.3);
        rate.put("5", 119.4);
        info.put("56", rate);
        rate = new HashMap<>();
        rate.put("1", 8.0);
        rate.put("2", 13.0);
        rate.put("3", 17.0);
        rate.put("4", 30.0);
        rate.put("5", 60.0);
        info.put("57", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 10.0);
        rate.put("3", 15.0);
        rate.put("4", 45.0);
        rate.put("5", 90.0);
        info.put("58", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("59", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 7.0);
        rate.put("3", 15.0);
        rate.put("4", 25.0);
        rate.put("5", 45.0);
        info.put("60", rate);
        rate = new HashMap<>();
        rate.put("1", 6.0);
        rate.put("2", 15.0);
        rate.put("3", 25.0);
        rate.put("4", 40.0);
        rate.put("5", 75.0);
        info.put("61", rate);
        rate = new HashMap<>();
        rate.put("1", 12.0);
        rate.put("2", 15.0);
        rate.put("3", 45.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("62", rate);
        rate = new HashMap<>();
        rate.put("1", 12.0);
        rate.put("2", 15.0);
        rate.put("3", 45.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("63", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 20.0);
        rate.put("3", 45.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("64", rate);
        rate = new HashMap<>();
        rate.put("1", 16.0);
        rate.put("2", 33.0);
        rate.put("3", 43.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("65", rate);
        rate = new HashMap<>();
        rate.put("1", 24.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("66", rate);
        rate = new HashMap<>();
        rate.put("1", 14.0);
        rate.put("2", 30.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("67", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("68", rate);
        rate = new HashMap<>();
        rate.put("1", 25.0);
        rate.put("2", 35.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("69", rate);
        rate = new HashMap<>();
        rate.put("1", 0.0);
        rate.put("2", 9.4);
        rate.put("3", 32.7);
        rate.put("4", 49.6);
        rate.put("5", 99.2);
        info.put("70", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 7.0);
        rate.put("3", 25.0);
        rate.put("4", 75.0);
        rate.put("5", 100.0);
        info.put("71", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 20.0);
        rate.put("3", 40.0);
        rate.put("4", 60.0);
        rate.put("5", 100.0);
        info.put("72", rate);
        rate = new HashMap<>();
        rate.put("1", 7.0);
        rate.put("2", 15.0);
        rate.put("3", 36.0);
        rate.put("4", 75.0);
        rate.put("5", 120.0);
        info.put("73", rate);
        rate = new HashMap<>();
        rate.put("1", 20.0);
        rate.put("2", 30.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("74", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 21.0);
        rate.put("3", 30.0);
        rate.put("4", 45.0);
        rate.put("5", 90.0);
        info.put("75", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 8.0);
        rate.put("3", 20.0);
        rate.put("4", 30.0);
        rate.put("5", 75.0);
        info.put("76", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 25.4);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("77", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 30.0);
        rate.put("3", 34.0);
        rate.put("4", 40.0);
        rate.put("5", 66.0);
        info.put("78", rate);
        rate = new HashMap<>();
        rate.put("1", 10.0);
        rate.put("2", 30.0);
        rate.put("3", 45.0);
        rate.put("4", 65.0);
        rate.put("5", 100.0);
        info.put("79", rate);
        rate = new HashMap<>();
        rate.put("1", 11.0);
        rate.put("2", 14.0);
        rate.put("3", 27.0);
        rate.put("4", 54.0);
        rate.put("5", 150.0);
        info.put("80", rate);
        rate = new HashMap<>();
        rate.put("1", 0.0);
        rate.put("2", 0.0);
        rate.put("3", 30.0);
        rate.put("4", 45.0);
        rate.put("5", 90.0);
        info.put("81", rate);
        rate = new HashMap<>();
        rate.put("1", 7.7);
        rate.put("2", 20.0);
        rate.put("3", 50.0);
        rate.put("4", 75.0);
        rate.put("5", 150.0);
        info.put("82", rate);
        rate = new HashMap<>();
        rate.put("1", 0.0);
        rate.put("2", 0.0);
        rate.put("3", 5.0);
        rate.put("4", 7.0);
        rate.put("5", 15.0);
        info.put("83", rate);
        rate = new HashMap<>();
        rate.put("1", 11.0);
        rate.put("2", 19.0);
        rate.put("3", 31.0);
        rate.put("4", 55.0);
        rate.put("5", 92.0);
        info.put("84", rate);
        rate = new HashMap<>();
        rate.put("1", 5.0);
        rate.put("2", 7.0);
        rate.put("3", 10.0);
        rate.put("4", 15.0);
        rate.put("5", 30.0);
        info.put("85", rate);
        rate = new HashMap<>();
        rate.put("1", 15.0);
        rate.put("2", 24.5);
        rate.put("3", 25.0);
        rate.put("4", 37.5);
        rate.put("5", 75.0);
        info.put("86", rate);
        rate = new HashMap<>();
        rate.put("1", 15.8);
        rate.put("2", 28.1);
        rate.put("3", 45.0);
        rate.put("4", 68.0);
        rate.put("5", 145.0);
        info.put("87", rate);
    }


    public static Double getRate(String region, String hp, String period) {
        Double horse_power;
        try {
            horse_power = Double.parseDouble(hp);
        } catch (NumberFormatException e) {
            return null;
        }
        HashMap<String, Double> reg = info.get(region);
        Double rate;
        if (horse_power < 100) {
            rate = reg.get("1");
        } else {
            if (horse_power >= 100 && horse_power < 150) {
                rate = reg.get("2");
            } else {
                if (horse_power >= 150 && horse_power < 200) {
                    rate = reg.get("3");
                } else {
                    if (horse_power >= 200 && horse_power < 250) {
                        rate = reg.get("4");
                    } else {
                        rate = reg.get("5");
                    }
                }
            }
        }

        switch (period) {
            case "1":
                rate /= 12;
                break;
            case "2":
                rate /= 12 / 2.0;
                break;
            case "3":
                rate /= 12 / 3.0;
                break;
            case "4":
                rate /= 12 / 4.0;
                break;
            case "5":
                rate /= 12 / 5.0;
                break;
            case "6":
                rate /= 12 / 6.0;
                break;
            case "7":
                rate /= 12 / 7.0;
                break;
            case "8":
                rate /= 12 / 8.0;
                break;
            case "9":
                rate /= 12 / 9.0;
                break;
            case "10":
                rate /= 12 / 10.0;
                break;
            case "11":
                rate /= 12 / 11.0;
                break;
            case "12":
                break;
        }
        return round(rate * horse_power, 2);
    }

    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();
        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }
}